version: "3.8"

services:
  # flask server scrapper
  scrapper:
    container_name: flask-scrapper
    build:
      context: ./scrapify-api/scrapper
      dockerfile: Dockerfile.test
    ports:
      - "8001:5000"
    networks:
      - scrapify-network
    environment:
      PORT: 5000
      FLASK_DEBUG: development
      FLASK_APP: server.py

networks:
  scrapify-network:
