version: "3.8"

services:
  nginx:
    container_name: gateway-api
    image: nginx:1.23.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - scrapify-network

  # flask server scrapper
  scrapper:
    container_name: flask-scrapper
    build:
      context: ./scrapify-api/scrapper
      dockerfile: Dockerfile.dev
    volumes:
      - ./scrapify-api/scrapper:/app
    ports:
      - "8001:5000"
    networks:
      - scrapify-network
    environment:
      PORT: 5000
      FLASK_DEBUG: development
      FLASK_APP: server.py

  cache:
    container_name: cache
    image: redis:6.2-alpine
    restart: always
    networks:
      - scrapify-network
    ports:
      - "6379:6379"
    # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - redis-cache:/data

  web-client:
    container_name: nextjs
    networks:
      - scrapify-network
    build:
      context: ./scrapify-app/web-scrapify
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
    volumes:
      - ./scrapify-app/web-scrapify:/app

networks:
  scrapify-network:

volumes:
  redis-cache:
