version: "3.8"

services:
  nginx:
    container_name: gateway-api
    image: nginx:1.23.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - scrapify-network

  scrapper:
    container_name: flask-scrapper
    build:
      context: ./scrapify-api/scrapper
      dockerfile: Dockerfile.dev
    volumes:
      - ./scrapify-api/scrapper:/app
    ports:
      - "8001:5000"
    networks:
      - scrapify-network
    environment:
      PORT: 5000
      FLASK_DEBUG: development
      FLASK_APP: server.py
      DB_URL: postgresql://postgres:postgres@flask_db:5432/postgres
    # command: python3 main.py

networks:
  scrapify-network:
