FROM python:3.11-alpine


WORKDIR /app

COPY requirements.txt .

RUN pip3 --no-cache-dir install -r requirements-dev.txt

COPY . .

ENV FLASK_APP server.py
ENV FLASK_DEBUG development


CMD ["python3", "server.py"]
